#ifndef ARACHNYAA_KERNEL_SYSCALL_H_
#define ARACHNYAA_KERNEL_SYSCALL_H_

#include <stdint.h>



enum {
  SYS_EXIT = 0,
  SYS_NS_BIND = 0x1,
  SYS_OPEN = 0x2,
  SYS_WRITE = 0x3,
  SYS_CAP_CLOSE = 0x4,
  SYS_PUTC = 0x5,
  SYS_CALL = 0x6,
  SYS_REPLY = 0x7,
  SYS_RECV = 0x8,
  SYS_SPAWN = 0x9,
  SYS_READ = 0xA,
  SYS_CLOSE = 0xB,
  SYS_EP_CREATE = 0xC,
  SYS_CAP_RESTRICT = 0xD,
  SYS_IRQ_CLAIM = 0xE,
  SYS_PROC_WAIT = 0xF,
  SYS_IRQ_WAIT = 0x10,
  SYS_IO_IN = 0x11,
  SYS_IO_OUT = 0x12,
  SYS_VSPACE_CREATE = 0x13,
  SYS_VSPACE_SELF = 0x14,
  SYS_PAGE_ALLOC = 0x15,
  SYS_VSPACE_MAP = 0x16,
  SYS_VSPACE_UNMAP = 0x17,
};

#endif // ARACHNYAA_KERNEL_SYSCALL_H_
